export const seoKeywordClusters = {
  core: [
    "startup valuation software",
    "startup valuation calculator",
    "AI startup valuation",
    "pre money valuation calculator",
    "post money valuation calculator",
    "investor ready valuation report",
    "startup valuation report",
    "startup valuation platform",
    "startup valuation methods",
    "startup fundraising valuation",
    "free startup valuation calculator",
    // India wedge + competitive
    "startup valuation India",
    "seed valuation India",
    "Indian startup valuation",
    "valuation India founder",
    "local comparables startup valuation",
  ],
  methods: [
    "Berkus method",
    "Berkus method calculator",
    "Scorecard valuation method",
    "VC method valuation",
    "DCF startup valuation",
    "startup comparables",
    "startup valuation multiples",
    "valuation assumptions",
    "valuation sensitivity analysis",
    "revenue quality startup valuation",
  ],
  stage: [
    "pre seed valuation",
    "angel round valuation",
    "seed round valuation",
    "pre revenue startup valuation",
    "SAFE valuation cap",
    "SAFE note valuation",
    "startup dilution",
    "founder dilution",
    "priced round vs SAFE",
  ],
  markets: [
    "startup valuation India",
    "startup valuation software India",
    "SaaS startup valuation",
    "AI SaaS valuation",
    "generative AI startup valuation",
    "fintech startup valuation",
    "marketplace startup valuation",
    "healthtech startup valuation",
    "climate tech startup valuation",
    "B2B startup valuation",
    "consumer startup valuation",
    "GitHub repo valuation",
    "open source startup valuation",
    "developer tool valuation",
    // Competitive differentiation
    "India vs global valuation tool",
    "local benchmarks startup valuation",
    "RBI rate valuation India",
    "MCA data valuation",
  ],
  investorPrep: [
    "startup investor checklist",
    "valuation checklist founders",
    "fundraising valuation questions",
    "startup valuation objections",
    "valuation slide pitch deck",
    "startup pitch deck valuation",
    "TAM SAM SOM startup",
    "startup market size valuation",
  ],
};

export const authoritySignals = {
  authorName: "Evaldam AI Valuation Research Team",
  authorUrl: "https://equidamai.com/methodology",
  reviewerName: "Evaldam AI Methodology Desk",
  reviewerUrl: "https://equidamai.com/methodology",
  organizationName: "Evaldam AI",
  organizationUrl: "https://equidamai.com",
  methodologyUrl: "https://equidamai.com/methodology",
  comparablesUrl: "https://equidamai.com/comparable-companies",
  freeValuationUrl: "https://equidamai.com/free-valuation",
  githubValuationUrl: "https://equidamai.com/github-valuation",
};

export const internalCitations = [
  {
    label: "Evaldam valuation methodology",
    href: "/methodology",
    url: "https://equidamai.com/methodology",
  },
  {
    label: "Comparable company context",
    href: "/comparable-companies",
    url: "https://equidamai.com/comparable-companies",
  },
  {
    label: "Free valuation preview",
    href: "/free-valuation",
    url: "https://equidamai.com/free-valuation",
  },
];
