services:
  - type: static
    name: evaldam-web
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://evaldam-api.onrender.com
